---
- name: Azure Create RG
  hosts: localhost
  connection: local

  tasks:
  - name: Get facts for all resource groups
    azure_rm_resourcegroup_info:
    register: azure_rg

  - name: Print Azure_rg 
    ansible.builtin.debug:
      msg_ "{{ azure_rg }}"
      